#!/usr/bin/env python3
"""Take a freshly deployed Netdisco to an instance with a login and an estate.

Netdisco has no write API and no way to add a device that does not answer SNMP,
so the seeding here is split by what the product supports:

  * `netdisco-do addpseudodevice` is the vendor's own answer to "record a device
     I cannot poll". It writes the device row and its ports through Netdisco's
     own code, and the vendor defaults it leaves behind -- vendor and os both
     literally "netdisco", model "pseudodevice", layers 00000100 -- are real
     product output that no fixture author would invent.
  * The password hash is generated by Netdisco's own passphrase plugin, run
     inside the container. safe_password_store defaults to true, so the stored
     value is bcrypt and matches() REJECTS anything that is not an RFC-2307
     string -- a hash computed out here would fail authentication rather than
     mismatch loudly.
  * Everything else is written with SQL, into Netdisco's real schema, because
     the columns concerned are only ever populated by an SNMP walk. The API
     still serves them through the real Dancer2 routes and the real DBIx::Class
     serialization, which is what this case is testing.

The estate is chosen so each row proves one decision:

  core-sw-01   Enriched to look like a polled switch, and given four device_ip
               aliases: its own address, a real second address, 127.0.0.1, and
               169.254.1.1. The last two are what make the address filter
               testable -- the platform would drop loopback on its own, but it
               KEEPS link-local, so an unfiltered 169.254 would reach the asset.
               The 127.0.0.1 alias also carries the DNS name "localhost", which
               must not become a hostname.
  edge-sw-02   Left exactly as addpseudodevice created it. No enrichment at all,
               so the assertions on it are assertions about Netdisco's defaults.
  three nodes  Two current, one last seen 90 days ago. The third must be aged
               out by max_age_days, which is applied by the script because the
               node route has no age parameter of its own.
"""

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request

BASE = os.environ["RZ_BASE"]
PROJECT = os.environ["RZ_PROJECT"]
COMPOSE_FILE = os.environ["RZ_COMPOSE_FILE"]

ADMIN_USER = "runzero"
ADMIN_PASSWORD = "RunZeroContainerTest123!"

CORE_IP = "10.99.7.11"
EDGE_IP = "10.99.7.12"

NODE_CURRENT = "00:1b:21:aa:bb:01"
NODE_LOCAL_ADMIN = "02:42:ac:11:00:99"
NODE_STALE = "00:1b:21:aa:bb:03"
NODE_IP = "10.99.7.101"


def compose(service, argv, timeout=600, check=True, env=None):
    full = ["docker", "compose", "-p", PROJECT, "-f", COMPOSE_FILE, "exec", "-T"]
    for key, value in (env or {}).items():
        full += ["-e", "%s=%s" % (key, value)]
    full += [service] + list(argv)
    proc = subprocess.run(full, capture_output=True, text=True, timeout=timeout)
    if check and proc.returncode != 0:
        sys.exit("`%s` failed (%d):\n%s\n%s" % (
            " ".join(argv), proc.returncode, proc.stdout[-2000:], proc.stderr[-2000:]))
    return proc.stdout or ""


def psql(statement, timeout=180):
    return compose("backend",
                   ["psql", "-h", "postgresql", "-U", "netdisco", "-d", "netdisco",
                    "-v", "ON_ERROR_STOP=1", "--no-align", "--tuples-only", "-c", statement],
                   timeout=timeout, env={"PGPASSWORD": "netdisco"})


def api(path, token, timeout=120):
    request = urllib.request.Request(
        BASE + path, headers={"Authorization": token, "Accept": "application/json"})
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as exc:
        sys.exit("GET %s failed: %s %s" % (path, exc.code, exc.read().decode()[:400]))


def login():
    body = json.dumps({}).encode()
    import base64
    credential = base64.b64encode(
        ("%s:%s" % (ADMIN_USER, ADMIN_PASSWORD)).encode()).decode()
    request = urllib.request.Request(BASE + "/login", data=body, method="POST", headers={
        "Authorization": "Basic " + credential,
        # Netdisco decides whether /login answers JSON or a 302 redirect purely
        # on the Accept header, so this is not decoration.
        "Accept": "application/json",
        "Content-Type": "application/json",
    })
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as exc:
        sys.exit("POST /login failed: %s %s" % (exc.code, exc.read().decode()[:400]))


def main():
    # Generated by Netdisco's own plugin, inside the container. See the module
    # docstring: matches() will not accept anything else.
    password_hash = compose("backend", [
        "/home/netdisco/perl5/bin/localenv", "perl", "-e",
        "use App::Netdisco::Environment; use Dancer qw(:script);"
        " use Dancer::Plugin::Passphrase;"
        " print passphrase(q{%s})->generate->rfc2307;" % ADMIN_PASSWORD,
    ]).strip()
    if not password_hash.startswith("{"):
        sys.exit("password hash does not look RFC-2307: %r" % password_hash[:80])

    psql("insert into users (username, password, admin, port_control, fullname) "
         "values ('%s', '%s', true, true, 'runZero Container Test')"
         % (ADMIN_USER, password_hash))

    compose("backend", ["netdisco-do", "addpseudodevice", "-d", CORE_IP,
                        "-e", "core-sw-01", "-p", "4"])
    compose("backend", ["netdisco-do", "addpseudodevice", "-d", EDGE_IP,
                        "-e", "edge-sw-02", "-p", "2"])

    # core-sw-01 only. edge-sw-02 stays as the product created it.
    psql("""
        update device set
          dns = 'core-sw-01.lab.example.com',
          description = 'Cisco IOS Software, C2960X Software',
          contact = 'netops@lab.example.com',
          location = 'Rack 4, Lab',
          model = 'WS-C2960X-24TS-L',
          vendor = 'cisco',
          os = 'ios',
          os_ver = '15.2(4)E7',
          serial = 'FDO1234X5YZ',
          mac = '00:1b:21:00:00:11',
          chassis_id = 'FDO1234X5YZ',
          snmp_ver = 2,
          snmp_class = 'SNMP::Info::Layer3::C3550',
          layers = '01001010',
          uptime = 123456789,
          last_macsuck = LOCALTIMESTAMP,
          last_arpnip = LOCALTIMESTAMP
        where ip = '%s'
    """ % CORE_IP)

    # Four aliases. The last two are the point: the platform filters loopback on
    # its own, but it KEEPS link-local, so 169.254.1.1 reaches the asset unless
    # the integration drops it. 'localhost' on the loopback alias is the
    # placeholder-hostname half of the same test.
    for alias, dns in [
        (CORE_IP, "core-sw-01.lab.example.com"),
        ("10.99.7.211", "core-sw-01-mgmt.lab.example.com"),
        ("127.0.0.1", "localhost"),
        ("169.254.1.1", ""),
    ]:
        psql("insert into device_ip (ip, alias, dns, port) values "
             "('%s', '%s', %s, 'Port1') on conflict do nothing"
             % (CORE_IP, alias, ("'%s'" % dns) if dns else "NULL"))

    for mac, port, vlan, age in [
        (NODE_CURRENT, "Port1", "10", 0),
        (NODE_LOCAL_ADMIN, "Port2", "20", 0),
        # 90 days stale. max_age_days defaults to 30, and the node route has no
        # age parameter, so this is the row that proves the script filters it.
        (NODE_STALE, "Port3", "30", 90),
    ]:
        psql("insert into node (mac, switch, port, vlan, active, time_first, "
             "time_recent, time_last) values ('%s', '%s', '%s', '%s', true, "
             "LOCALTIMESTAMP - interval '180 days', "
             "LOCALTIMESTAMP - interval '%d days', "
             "LOCALTIMESTAMP - interval '%d days')" % (mac, CORE_IP, port, vlan, age, age))

    psql("insert into node_ip (mac, ip, active, dns, time_first, time_last) values "
         "('%s', '%s', true, 'host-a.lab.example.com', "
         "LOCALTIMESTAMP - interval '180 days', LOCALTIMESTAMP)" % (NODE_CURRENT, NODE_IP))

    session = login()
    token = str(session.get("api_key") or "")
    if len(token) < 16:
        sys.exit("POST /login returned no usable api_key: %s" % json.dumps(session)[:300])
    if "," in token:
        sys.exit("the api_key contains a comma and cannot be passed as a kwarg")

    # Read the estate back through the API, both to prove the token works and to
    # confirm the rows are visible on the route the integration actually calls.
    devices = api("/api/v1/search/device?limit=50&offset=0&fields=ip,dns,name,model,vendor,os,is_pseudo", token)
    ips = sorted(str(d.get("ip")) for d in devices if isinstance(d, dict))
    if ips != sorted([CORE_IP, EDGE_IP]):
        sys.exit("the device search returned %s, expected %s" % (ips, [CORE_IP, EDGE_IP]))

    nodes = api("/api/v1/object/device/%s/nodes?active_only=true" % CORE_IP, token)
    if len(nodes) != 3:
        sys.exit("expected 3 located nodes on %s, the API returned %d" % (CORE_IP, len(nodes)))

    print(json.dumps({
        "core_ip": CORE_IP,
        "edge_ip": EDGE_IP,
        "node_current": NODE_CURRENT,
        "node_local_admin": NODE_LOCAL_ADMIN,
        "node_stale": NODE_STALE,
        "node_ip": NODE_IP,
        # The integration performs its own /login, so the token is not passed as
        # a kwarg. It is published only so a failing run can be reproduced by
        # hand against the same instance.
        "api_key": token,
    }))


if __name__ == "__main__":
    main()
